use serde::{Serialize, Deserialize};

#[derive(Debug, Clone, PartialEq, Copy, Serialize, Deserialize)]
pub enum Keyword {
    // Control flow keywords
    If,
    Elif,
    Else,
    Do,
    While,
    For,
    Try,
    Fail,
    End,
    Break,
    Continue,
    In,
    // Function and variable keywords
    Let,
    From,
    Back,
    Send,
    Del,
    Fn,
    Call,
    True,
    False,
    //Atributes and modifiers
    Sure,
    Stay,
    Fast,
    Flat,
    Old,
    //Input/Output keywords
    Print,
    Ask,
    Read,
    Save,
    //graphics keywords
    Ui,
    Btn,
    Txt,
    Img,
    Vid,
    Canvas,
    Div,
    Click,
    Window,
    //other keywords
    Tick,
    Wait,
    As,
    Log,
    Run,
    Exit,

}

impl Keyword {
    pub fn from_str(s: &str) -> Option<Keyword> {
        match s.to_lowercase().as_str() {
            "if" => Some(Keyword::If),
            "elif" => Some(Keyword::Elif),
            "else" => Some(Keyword::Else),
            "do" => Some(Keyword::Do),
            "while" => Some(Keyword::While),
            "for" => Some(Keyword::For),
            "try" => Some(Keyword::Try),
            "fail" => Some(Keyword::Fail),
            "end" => Some(Keyword::End),
            "break" => Some(Keyword::Break),
            "continue" => Some(Keyword::Continue),
            "in" => Some(Keyword::In),
            "let" => Some(Keyword::Let),
            "from" => Some(Keyword::From),
            "back" => Some(Keyword::Back),
            "send" => Some(Keyword::Send),
            "del" => Some(Keyword::Del),
            "fn" => Some(Keyword::Fn),
            "call" => Some(Keyword::Call),
            "true" => Some(Keyword::True),
            "false" => Some(Keyword::False),
            "sure" => Some(Keyword::Sure),
            "stay" => Some(Keyword::Stay),
            "fast" => Some(Keyword::Fast),
            "flat" => Some(Keyword::Flat),
            "old" => Some(Keyword::Old),
            "print" => Some(Keyword::Print),
            "ask" => Some(Keyword::Ask),
            "read" => Some(Keyword::Read),
            "save" => Some(Keyword::Save),
            "ui" => Some(Keyword::Ui),
            "btn" => Some(Keyword::Btn),
            "txt" => Some(Keyword::Txt),
            "img" => Some(Keyword::Img),
            "vid" => Some(Keyword::Vid),
            "canvas" => Some(Keyword::Canvas),
            "div" => Some(Keyword::Div),
            "click" => Some(Keyword::Click),
            "window" => Some(Keyword::Window),
            "tick" => Some(Keyword::Tick),
            "wait" => Some(Keyword::Wait),
            "as" => Some(Keyword::As),
            "log" => Some(Keyword::Log),
            "run" => Some(Keyword::Run),
            "exit" => Some(Keyword::Exit),

            _ => None,
        }
    }
}
